apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-app-deployment
  labels:
    app: springboot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: static-site
        image: us-central1-docker.pkg.dev/nodal-crawler-460115-d2/your-artifact-registry-repo/static-site:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"