apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: us-central1-docker.pkg.dev/nodal-crawler-460115-d2/your-artifact-registry-repo/static-site
    newTag: latest

resources:
  - deployment.yaml
  - service.yaml